### ISSUE TITLE
Mustache Template Support

### ISSUE THREAD

**Issue by activestylus** [lotus/view#30]
I've used erb/slim for years, but nowadays mustache is all I use in order to share templates between server and client. While I can technically use it with Lotus by calling Mustache.render from the controller action, I miss out on the rendering conventions (configured template folder, auto-rendering based on view classes, etc)

Any chance of including mustache support in future versions of Lotus::View?

**Comment by joneslee85** [comment]
Thanks for reporting this, I close this ticket for now as it is become too old without getting enough attention.
