### ISSUE TITLE
Inheriting from core class, Hash

### ISSUE THREAD

**Issue by jc00ke** [lotus/view#55]
Was browsing through the code and saw that the `LayoutRegistry` [inherits](https://github.com/lotus/view/blob/07b287168b029564e40cc53e754be58b8e9aa997/lib/lotus/view/rendering/layout_registry.rb#L24) from `Hash`.

Thoughts on composing a `@registry = {}` instead of using inheritance?

https://github.com/lotus/utils/pull/14

**Comment by jodosha** [comment]
@jc00ke `LayoutRegistry` has that design before we discussed about this topic in lotus/utils#14.

While `Utils::String` and `Utils::Hash` are public, this class isn't. Because you care about this, would you mind to craft a PR to improve it? Thank you.

**Comment by jc00ke** [comment]
I'd be happy to.
