### ISSUE TITLE
LayoutScope raises a ::NoMethodError even when that particular mehod was present

### ISSUE THREAD

**Issue by mrubi** [lotus/view#83]
In the Lotus::View::Rendering::LayoutScope class we have the following implementation:

```ruby
def method_missing(m, *args, &blk)
   if @scope.respond_to?(m)
      @scope.__send__(m, *args, &blk)
   elsif layout.respond_to?(m)
      layout.__send__(m, *args, &blk)
   else
      ::Lotus::View::Escape.html(super)
   end
rescue ::NameError
   ::Kernel.raise ::NoMethodError.new("undefined method `#{ m }' for #{ self.inspect }", m)
end
```

which always raises a NoMethodError for its own method missing, even if the scope or layout did responed to that method.

Example:

```ruby
module Web::Views::LandingPage
  class Index
	include Web::View

	def title
	  'I do respond to :title, but this String does not respond to :summarize '.summarize
	end
  end
end
```

and also

```ruby
module Web::Views::LandingPage
   class Index
      include Web::View

      def title
         sumarize long_title # typo in :sumarize
      end

      protected

      def long_title
         'I am a very long title not suitable to be the title of the page'
      end

      def summarize(text)
         # shortern the text somehow
      end
   end
end
```

In both examples the LayoutScope raises a NoMethodError  as if it did not respond to :title, which can be a bit missleading for finding the actual error.

I couldn't come up with a clear solution propossal, as the ::NoMethodError doesn't seem to have the receiver of the missing method, so I was hoping that somebody could figure out how to let the correct NoMethodError errors hit the surface?

**Comment by jodosha** [comment]
@mrubi Thanks for reporting this. That's really annoying.

I've prepared a PR to fix it, can you please try and report if it fix your problem? Thank you very much!! :cake:

**Comment by mrubi** [comment]
@jodosha Yes, it fixed it!
Thanks!
